[package]
name = "rust-compiler-2"
version = "0.1.0"
edition = "2024"

[dependencies]
color-backtrace = "0.7.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
[workspace]
